weapons = [
    "Sploosh-o-matic",
    "Neo Sploosh-o-matic",
    "Sploosh-o-matic 7",
    "Splattershot Jr.",
    "Custom Splattershot Jr.",
    "Kensa Splattershot Jr.",
    "Splash-o-matic",
    "Neo Splash-o-matic",
    "Aerospray MG",
    "Aerospray RG",
    "Aerospray PG",
    "Splattershot",
    "Tentatek Splattershot",
    "Kensa Splattershot",
    ".52 Gal",
    ".52 Gal Deco",
    "Kensa .52 Gal",
    "N-ZAP '85",
    "N-ZAP '89",
    "N-ZAP '83",
    "Splattershot Pro",
    "Forge Splattershot Pro",
    "Kensa Splattershot Pro",
    ".96 Gal",
    ".96 Gal Deco",
    "Jet Squelcher",
    "Custom Jet Squelcher",
    "L-3 Nozzlenose",
    "L-3 Nozzlenose D",
    "Kensa L-3 Nozzlenose",
    "H-3 Nozzlenose",
    "H-3 Nozzlenose D",
    "Cherry H-3 Nozzlenose",
    "Squeezer",
    "Foil Squeezer",
    "Luna Blaster",
    "Luna Blaster Neo",
    "Kensa Luna Blaster",
    "Blaster",
    "Custom Blaster",
    "Range Blaster",
    "Custom Range Blaster",
    "Grim Range Blaster",
    "Rapid Blaster",
    "Rapid Blaster Deco",
    "Kensa Rapid Blaster",
    "Rapid Blaster Pro",
    "Rapid Blaster Pro Deco",
    "Clash Blaster",
    "Clash Blaster Neo",
    "Carbon Roller",
    "Carbon Roller Deco",
    "Splat Roller",
    "Krak-On Splat Roller",
    "Kensa Splat Roller",
    "Dynamo Roller",
    "Gold Dynamo Roller",
    "Kensa Dynamo Roller",
    "Flingza Roller",
    "Foil Flingza Roller",
    "Inkbrush",
    "Inkbrush Nouveau",
    "Permanent Inkbrush",
    "Octobrush",
    "Octobrush Nouveau",
    "Kensa Octobrush",
    "Classic Squiffer",
    "New Squiffer",
    "Fresh Squiffer",
    "Splat Charger",
    "Firefin Splat Charger",
    "Kensa Charger",
    "Splatterscope",
    "Firefin Splatterscope",
    "Kensa Splatterscope",
    "E-liter 4K",
    "Custom E-liter 4K",
    "E-liter 4K Scope",
    "Custom E-liter 4K Scope",
    "Bamboozler 14 Mk I",
    "Bamboozler 14 Mk II",
    "Bamboozler 14 Mk III",
    "Goo Tuber",
    "Custom Goo Tuber",
    "Slosher",
    "Slosher Deco",
    "Soda Slosher",
    "Tri-Slosher",
    "Tri-Slosher Nouveau",
    "Sloshing Machine",
    "Sloshing Machine Neo",
    "Kensa Sloshing Machine",
    "Bloblobber",
    "Bloblobber Deco",
    "Explosher",
    "Custom Explosher",
    "Mini Splatling",
    "Zink Mini Splatling",
    "Kensa Mini Splatling",
    "Heavy Splatling",
    "Heavy Splatling Deco",
    "Heavy Splatling Remix",
    "Hydra Splatling",
    "Custom Hydra Splatling",
    "Ballpoint Splatling",
    "Ballpoint Splatling Nouveau",
    "Nautilus 47",
    "Nautilus 79",
    "Dapple Dualies",
    "Dapple Dualies Nouveau",
    "Clear Dapple Dualies",
    "Splat Dualies",
    "Enperry Splat Dualies",
    "Kensa Splat Dualies",
    "Glooga Dualies",
    "Glooga Dualies Deco",
    "Kensa Glooga Dualies",
    "Dualie Squelchers",
    "Custom Dualie Squelchers",
    "Dark Tetra Dualies",
    "Light Tetra Dualies",
    "Splat Brella",
    "Sorella Brella",
    "Tenta Brella",
    "Tenta Sorella Brella",
    "Tenta Camo Brella",
    "Undercover Brella",
    "Undercover Sorella Brella",
    "Kensa Undercover Brella",
]

weapons_upper = [
    "SPLOOSH-O-MATIC",
    "NEO SPLOOSH-O-MATIC",
    "SPLOOSH-O-MATIC 7",
    "SPLATTERSHOT JR.",
    "CUSTOM SPLATTERSHOT JR.",
    "KENSA SPLATTERSHOT JR.",
    "SPLASH-O-MATIC",
    "NEO SPLASH-O-MATIC",
    "AEROSPRAY MG",
    "AEROSPRAY RG",
    "AEROSPRAY PG",
    "SPLATTERSHOT",
    "TENTATEK SPLATTERSHOT",
    "KENSA SPLATTERSHOT",
    ".52 GAL",
    ".52 GAL DECO",
    "KENSA .52 GAL",
    "N-ZAP '85",
    "N-ZAP '89",
    "N-ZAP '83",
    "SPLATTERSHOT PRO",
    "FORGE SPLATTERSHOT PRO",
    "KENSA SPLATTERSHOT PRO",
    ".96 GAL",
    ".96 GAL DECO",
    "JET SQUELCHER",
    "CUSTOM JET SQUELCHER",
    "L-3 NOZZLENOSE",
    "L-3 NOZZLENOSE D",
    "KENSA L-3 NOZZLENOSE",
    "H-3 NOZZLENOSE",
    "H-3 NOZZLENOSE D",
    "CHERRY H-3 NOZZLENOSE",
    "SQUEEZER",
    "FOIL SQUEEZER",
    "LUNA BLASTER",
    "LUNA BLASTER NEO",
    "KENSA LUNA BLASTER",
    "BLASTER",
    "CUSTOM BLASTER",
    "RANGE BLASTER",
    "CUSTOM RANGE BLASTER",
    "GRIM RANGE BLASTER",
    "RAPID BLASTER",
    "RAPID BLASTER DECO",
    "KENSA RAPID BLASTER",
    "RAPID BLASTER PRO",
    "RAPID BLASTER PRO DECO",
    "CLASH BLASTER",
    "CLASH BLASTER NEO",
    "CARBON ROLLER",
    "CARBON ROLLER DECO",
    "SPLAT ROLLER",
    "KRAK-ON SPLAT ROLLER",
    "KENSA SPLAT ROLLER",
    "DYNAMO ROLLER",
    "GOLD DYNAMO ROLLER",
    "KENSA DYNAMO ROLLER",
    "FLINGZA ROLLER",
    "FOIL FLINGZA ROLLER",
    "INKBRUSH",
    "INKBRUSH NOUVEAU",
    "PERMANENT INKBRUSH",
    "OCTOBRUSH",
    "OCTOBRUSH NOUVEAU",
    "KENSA OCTOBRUSH",
    "CLASSIC SQUIFFER",
    "NEW SQUIFFER",
    "FRESH SQUIFFER",
    "SPLAT CHARGER",
    "FIREFIN SPLAT CHARGER",
    "KENSA CHARGER",
    "SPLATTERSCOPE",
    "FIREFIN SPLATTERSCOPE",
    "KENSA SPLATTERSCOPE",
    "E-LITER 4K",
    "CUSTOM E-LITER 4K",
    "E-LITER 4K SCOPE",
    "CUSTOM E-LITER 4K SCOPE",
    "BAMBOOZLER 14 MK I",
    "BAMBOOZLER 14 MK II",
    "BAMBOOZLER 14 MK III",
    "GOO TUBER",
    "CUSTOM GOO TUBER",
    "SLOSHER",
    "SLOSHER DECO",
    "SODA SLOSHER",
    "TRI-SLOSHER",
    "TRI-SLOSHER NOUVEAU",
    "SLOSHING MACHINE",
    "SLOSHING MACHINE NEO",
    "KENSA SLOSHING MACHINE",
    "BLOBLOBBER",
    "BLOBLOBBER DECO",
    "EXPLOSHER",
    "CUSTOM EXPLOSHER",
    "MINI SPLATLING",
    "ZINK MINI SPLATLING",
    "KENSA MINI SPLATLING",
    "HEAVY SPLATLING",
    "HEAVY SPLATLING DECO",
    "HEAVY SPLATLING REMIX",
    "HYDRA SPLATLING",
    "CUSTOM HYDRA SPLATLING",
    "BALLPOINT SPLATLING",
    "BALLPOINT SPLATLING NOUVEAU",
    "NAUTILUS 47",
    "NAUTILUS 79",
    "DAPPLE DUALIES",
    "DAPPLE DUALIES NOUVEAU",
    "CLEAR DAPPLE DUALIES",
    "SPLAT DUALIES",
    "ENPERRY SPLAT DUALIES",
    "KENSA SPLAT DUALIES",
    "GLOOGA DUALIES",
    "GLOOGA DUALIES DECO",
    "KENSA GLOOGA DUALIES",
    "DUALIE SQUELCHERS",
    "CUSTOM DUALIE SQUELCHERS",
    "DARK TETRA DUALIES",
    "LIGHT TETRA DUALIES",
    "SPLAT BRELLA",
    "SORELLA BRELLA",
    "TENTA BRELLA",
    "TENTA SORELLA BRELLA",
    "TENTA CAMO BRELLA",
    "UNDERCOVER BRELLA",
    "UNDERCOVER SORELLA BRELLA",
    "KENSA UNDERCOVER BRELLA",
]

weapons_english_internal = {
    "Baller": "AquaBall",
    "SquidForce": "B00",
    "Zink": "B01",
    "Krak-On": "B02",
    "Rockenberg": "B03",
    "Zekko": "B04",
    "Forge": "B05",
    "Firefin": "B06",
    "Skalop": "B07",
    "Splash Mob": "B08",
    "Inkline": "B09",
    "Tentatek": "B10",
    "Takoroka": "B11",
    "Annaki": "B15",
    "Enperry": "B16",
    "Toni Kensa": "B17",
    "Grizzco": "B97",
    "Cuttlegear": "B98",
    "amiibo": "B99",
    "": "Unknown",
    "Fire Rate": "Blaze",
    "Bomb Defense Up DX": "BombDamage_Reduction",
    "Sub Power Up": "BombDistance_Up",
    "Curling Bomb": "Bomb_MissionCurling",
    "Autobomb": "Bomb_Robo",
    "Splat Bomb": "Bomb_Splash",
    "Fizzy Bomb": "Bomb_Piyo",
    "Burst Bomb": "Bomb_Quick",
    "Suction Bomb": "Bomb_Suction",
    "Torpedo": "Bomb_Tako",
    "Charge Speed": "Charge",
    "Grizzco Charger": "Charger_CoopSpark",
    "Goo Tuber": "Charger_Keeper_00",
    "Custom Goo Tuber": "Charger_Keeper_01",
    "Bamboozler 14 Mk I": "Charger_Light_00",
    "Bamboozler 14 Mk II": "Charger_Light_01",
    "Bamboozler 14 Mk III": "Charger_Light_02",
    "E-liter 4K Scope": "Charger_LongScope_00",
    "Custom E-liter 4K Scope": "Charger_LongScope_01",
    "E-liter 4K": "Charger_Long_00",
    "Custom E-liter 4K": "Charger_Long_01",
    "Hero Charger": "Charger_MissionNormalLv1",
    "Splatterscope": "Charger_NormalScope_00",
    "Firefin Splatterscope": "Charger_NormalScope_01",
    "Kensa Splatterscope": "Charger_NormalScope_02",
    "Splat Charger": "Charger_Normal_00",
    "Firefin Splat Charger": "Charger_Normal_01",
    "Kensa Charger": "Charger_Normal_02",
    "Hero Charger Replica": "Charger_Normal_H",
    "Classic Squiffer": "Charger_Quick_00",
    "New Squiffer": "Charger_Quick_01",
    "Fresh Squiffer": "Charger_Quick_02",
    "School Uniform": "Clt_AMB000",
    "Samurai Jacket": "Clt_AMB001",
    "Power Armor": "Clt_AMB002",
    "School Cardigan": "Clt_AMB003",
    "Squinja Suit": "Clt_AMB004",
    "Power Armor Mk I": "Clt_AMB005",
    "Pearlescent Hoodie": "Clt_AMB006",
    "Marinated Top": "Clt_AMB007",
    "Enchanted Robe": "Clt_AMB008",
    "Steel Platemail": "Clt_AMB009",
    "Fresh Fish Gloves": "Clt_AMB010",
    "Squiddor Polo": "Clt_COP100",
    "Anchor Life Vest": "Clt_COP101",
    "Juice Parka": "Clt_COP102",
    "Garden Gear": "Clt_COP103",
    "Crustwear XXL": "Clt_COP104",
    "North-Country Parka": "Clt_COP105",
    "Octoleet Armor": "Clt_COP106",
    "Record Shop Look EP": "Clt_COP107",
    "Dev Uniform": "Clt_COP108",
    "Office Attire": "Clt_COP109",
    "SRL Coat": "Clt_COP110",
    "Mecha Body - AKM": "Clt_CRC000",
    "Basic Tee": "Clt_FST001",
    "Fresh Octo Tee": "Clt_FST002",
    "Splatfest Tee": "Clt_HAP001",
    "Olive Ski Jacket": "Clt_JKT000",
    "Takoroka Nylon Vintage": "Clt_JKT001",
    "Berry Ski Jacket": "Clt_JKT002",
    "Varsity Jacket": "Clt_JKT003",
    "School Jersey": "Clt_JKT004",
    "Green Cardigan": "Clt_JKT005",
    "Black Inky Rider": "Clt_JKT006",
    "White Inky Rider": "Clt_JKT007",
    "Retro Gamer Jersey": "Clt_JKT008",
    "Orange Cardigan": "Clt_JKT009",
    "Forge Inkling Parka": "Clt_JKT010",
    "Forge Octarian Jacket": "Clt_JKT011",
    "Blue Sailor Suit": "Clt_JKT012",
    "White Sailor Suit": "Clt_JKT013",
    "Squid Satin Jacket": "Clt_JKT014",
    "Zapfish Satin Jacket": "Clt_JKT015",
    "Krak-On 528": "Clt_JKT016",
    "Chilly Mountain Coat": "Clt_JKT017",
    "Takoroka Windcrusher": "Clt_JKT018",
    "Matcha Down Jacket": "Clt_JKT019",
    "FA-01 Jacket": "Clt_JKT020",
    "FA-01 Reversed": "Clt_JKT021",
    "Pullover Coat": "Clt_JKT022",
    "Kensa Coat": "Clt_JKT023",
    "Birded Corduroy Jacket": "Clt_JKT024",
    "Deep-Octo Satin Jacket": "Clt_JKT025",
    "Zekko Redleaf Coat": "Clt_JKT026",
    "Eggplant Mountain Coat": "Clt_JKT027",
    "Zekko Jade Coat": "Clt_JKT028",
    "Light Bomber Jacket": "Clt_JKT029",
    "Brown FA-11 Bomber": "Clt_JKT030",
    "Gray FA-11 Bomber": "Clt_JKT031",
    "Milky Eminence Jacket": "Clt_JKT032",
    "Navy Eminence Jacket": "Clt_JKT033",
    "Tumeric Zekko Coat": "Clt_JKT034",
    "Custom Painted F-3 ": "Clt_JKT035",
    "Dark Bomber Jacket": "Clt_JKT036",
    "Moist Ghillie Suit": "Clt_JKT037",
    "White Leather F-3": "Clt_JKT038",
    "Chili-Pepper Ski Jacket": "Clt_JKT039",
    "Whale-Knit Sweater": "Clt_JKT040",
    "Rockin' Leather Jacket": "Clt_JKT041",
    "Kung-Fu Zip-Up": "Clt_JKT042",
    "Panda Kung-Fu Zip-Up": "Clt_JKT043",
    "Sennyu Suit": "Clt_JKT044",
    "Hero Jacket Replica": "Clt_MSN000",
    "Armor Jacket Replica": "Clt_MSN004",
    "Hero Hoodie Replica": "Clt_MSN101",
    "Neo Octoling Armor": "Clt_MSN104",
    "Null Armor Replica": "Clt_MSN105",
    "Old-Timey Clothes": "Clt_MSN106",
    "Shrimp-Pink Polo": "Clt_PLO000",
    "Striped Rugby": "Clt_PLO001",
    "Tricolor Rugby": "Clt_PLO002",
    "Sage Polo": "Clt_PLO003",
    "Black Polo": "Clt_PLO004",
    "Cycling Shirt": "Clt_PLO005",
    "Cycle King Jersey": "Clt_PLO006",
    "Slipstream United": "Clt_PLO007",
    "FC Albacore": "Clt_PLO008",
    "Camo Zip Hoodie": "Clt_PRK000",
    "Green Zip Hoodie": "Clt_PRK001",
    "Zekko Hoodie": "Clt_PRK002",
    "Shirt with Blue Hoodie": "Clt_PRK004",
    "Grape Hoodie": "Clt_PRK005",
    "Gray Hoodie": "Clt_PRK006",
    "Hothouse Hoodie": "Clt_PRK007",
    "Pink Hoodie": "Clt_PRK008",
    "Olive Zekko Parka": "Clt_PRK009",
    "Black Hoodie": "Clt_PRK010",
    "Octo Support Hoodie": "Clt_PRK011",
    "Octoling Armor": "Clt_RVL000",
    "Lumberjack Shirt": "Clt_SHT000",
    "Rodeo Shirt": "Clt_SHT001",
    "Green-Check Shirt": "Clt_SHT002",
    "White Shirt": "Clt_SHT003",
    "Urchins Jersey": "Clt_SHT004",
    "Aloha Shirt": "Clt_SHT005",
    "Red-Check Shirt": "Clt_SHT006",
    "Baby-Jelly Shirt": "Clt_SHT007",
    "Baseball Jersey": "Clt_SHT008",
    "Gray Mixed Shirt": "Clt_SHT009",
    "Vintage Check Shirt": "Clt_SHT010",
    "Round-Collar Shirt": "Clt_SHT011",
    "Logo Aloha Shirt": "Clt_SHT012",
    "Striped Shirt": "Clt_SHT013",
    "Linen Shirt": "Clt_SHT014",
    "Shirt & Tie": "Clt_SHT015",
    "Hula Punk Shirt": "Clt_SHT017",
    "Octobowler Shirt": "Clt_SHT018",
    "Inkfall Shirt": "Clt_SHT019",
    "Crimson Parashooter": "Clt_SHT020",
    "Baby-Jelly Shirt & Tie": "Clt_SHT021",
    "Prune Parashooter": "Clt_SHT022",
    "Red Hula Punk with Tie": "Clt_SHT023",
    "Chili Octo Aloha": "Clt_SHT024",
    "Annaki Flannel Hoodie": "Clt_SHT025",
    "Ink-Wash Shirt": "Clt_SHT026",
    "Dots-On-Dots Shirt": "Clt_SHT027",
    "Toni K. Baseball Jersey": "Clt_SHT028",
    "Online Jersey": "Clt_SHT029",
    "Gray College Sweat": "Clt_SWT000",
    "Squidmark Sweat": "Clt_SWT001",
    "Retro Sweat": "Clt_SWT002",
    "Firefin Navy Sweat": "Clt_SWT003",
    "Navy College Sweat": "Clt_SWT004",
    "Reel Sweat": "Clt_SWT005",
    "Anchor Sweat": "Clt_SWT006",
    "Negative Longcuff Sweater": "Clt_SWT007",
    "Short Knit Layers": "Clt_SWT008",
    "Positive Longcuff Sweater": "Clt_SWT009",
    "Annaki Blue Cuff": "Clt_SWT010",
    "Annaki Yellow Cuff": "Clt_SWT011",
    "Annaki Red Cuff": "Clt_SWT012",
    "N-Pacer Sweat": "Clt_SWT013",
    "Octarian Retro": "Clt_SWT014",
    "Takoroka Jersey": "Clt_SWT015",
    "White Striped LS": "Clt_TEL000",
    "Black LS": "Clt_TEL001",
    "Purple Camo LS": "Clt_TEL002",
    "Navy Striped LS": "Clt_TEL003",
    "Zekko Baseball LS": "Clt_TEL004",
    "Varsity Baseball LS": "Clt_TEL005",
    "Black Baseball LS": "Clt_TEL006",
    "White Baseball LS": "Clt_TEL007",
    "White LS": "Clt_TEL008",
    "Green Striped LS": "Clt_TEL009",
    "Squidmark LS": "Clt_TEL010",
    "Zink LS": "Clt_TEL011",
    "Striped Peaks LS": "Clt_TEL012",
    "Pink Easy-Stripe Shirt": "Clt_TEL013",
    "Inkopolis Squaps Jersey": "Clt_TEL014",
    "Annaki Drive Tee ": "Clt_TEL015",
    "Lime Easy-Stripe Shirt": "Clt_TEL016",
    "Annaki Evolution Tee": "Clt_TEL017",
    "Zekko Long Carrot Tee": "Clt_TEL018",
    "Zekko Long Radish Tee": "Clt_TEL019",
    "Black Cuttlegear LS": "Clt_TEL020",
    "Takoroka Crazy Baseball LS": "Clt_TEL021",
    "Red Cuttlegear LS": "Clt_TEL022",
    "Khaki 16-Bit FishFry": "Clt_TEL023",
    "Blue 16-Bit FishFry": "Clt_TEL024",
    "White Tee": "Clt_TES000",
    "Black Squideye": "Clt_TES001",
    "Sky-Blue Squideye": "Clt_TES003",
    "Rockenberg White": "Clt_TES004",
    "Rockenberg Black": "Clt_TES005",
    "Black Tee": "Clt_TES006",
    "Sunny-Day Tee": "Clt_TES007",
    "Rainy-Day Tee": "Clt_TES008",
    "Reggae Tee": "Clt_TES009",
    "Fugu Tee": "Clt_TES010",
    "Mint Tee": "Clt_TES011",
    "Grape Tee": "Clt_TES012",
    "Red Vector Tee": "Clt_TES013",
    "Gray Vector Tee": "Clt_TES014",
    "Blue Peaks Tee": "Clt_TES015",
    "Ivory Peaks Tee": "Clt_TES016",
    "Squid-Stitch Tee": "Clt_TES017",
    "Pirate-Stripe Tee": "Clt_TES018",
    "Sailor-Stripe Tee": "Clt_TES019",
    "White 8-Bit FishFry": "Clt_TES020",
    "Black 8-Bit FishFry": "Clt_TES021",
    "White Anchor Tee": "Clt_TES022",
    "Black Anchor Tee": "Clt_TES023",
    "Carnivore Tee": "Clt_TES026",
    "Pearl Tee": "Clt_TES027",
    "Octo Tee": "Clt_TES028",
    "Herbivore Tee": "Clt_TES029",
    "Black V-Neck Tee": "Clt_TES030",
    "White Deca Logo Tee": "Clt_TES031",
    "Half-Sleeve Sweater": "Clt_TES032",
    "King Jersey": "Clt_TES033",
    "Gray 8-Bit FishFry": "Clt_TES034",
    "White V-Neck Tee": "Clt_TES035",
    "White Urchin Rock Tee": "Clt_TES036",
    "Black Urchin Rock Tee": "Clt_TES037",
    "Wet Floor Band Tee": "Clt_TES038",
    "Squid Squad Band Tee": "Clt_TES039",
    "Navy Deca Logo Tee": "Clt_TES040",
    "Mister Shrug Tee": "Clt_TES041",
    "Chirpy Chips Band Tee": "Clt_TES042",
    "Hightide Era Band Tee": "Clt_TES043",
    "Red V-Neck Limited Tee": "Clt_TES044",
    "Green V-Neck Limited Tee": "Clt_TES045",
    "\u03c9-3 Tee": "Clt_TES046",
    "Annaki Polpo-Pic Tee": "Clt_TES047",
    "Firewave Tee": "Clt_TES048",
    "Takoroka Galactic Tie Dye": "Clt_TES049",
    "Takoroka Rainbow Tie Dye": "Clt_TES050",
    "Missus Shrug Tee": "Clt_TES051",
    "League Tee": "Clt_TES052",
    "Friend Tee": "Clt_TES053",
    "Tentatek Slogan Tee": "Clt_TES054",
    "Icewave Tee": "Clt_TES055",
    "Octoking HK Jersey": "Clt_TES056",
    "Dakro Nana Tee": "Clt_TES057",
    "Dakro Golden Tee": "Clt_TES058",
    "Black Velour Octoking Tee ": "Clt_TES059",
    "Green Velour Octoking Tee": "Clt_TES060",
    "SWC Logo Tee": "Clt_TES061",
    "White Layered LS": "Clt_TLY000",
    "Yellow Layered LS": "Clt_TLY001",
    "Camo Layered LS": "Clt_TLY002",
    "Black Layered LS": "Clt_TLY003",
    "Zink Layered LS": "Clt_TLY004",
    "Layered Anchor LS": "Clt_TLY005",
    "Choco Layered LS": "Clt_TLY006",
    "Part-Time Pirate": "Clt_TLY007",
    "Layered Vector LS": "Clt_TLY008",
    "Green Tee": "Clt_TLY009",
    "Red Tentatek Tee": "Clt_TLY010",
    "Blue Tentatek Tee": "Clt_TLY011",
    "Octo Layered LS": "Clt_TLY012",
    "Squid Yellow Layered LS": "Clt_TLY013",
    "B-ball Jersey (Home)": "Clt_TNK000",
    "B-ball Jersey (Away)": "Clt_TNK001",
    "White King Tank": "Clt_TNK003",
    "Slash King Tank": "Clt_TNK004",
    "Navy King Tank": "Clt_TNK005",
    "Lob-Stars Jersey": "Clt_TNK006",
    "Mountain Vest": "Clt_VST000",
    "Forest Vest": "Clt_VST001",
    "Dark Urban Vest": "Clt_VST002",
    "Yellow Urban Vest": "Clt_VST003",
    "Squid-Pattern Waistcoat": "Clt_VST004",
    "Squidstar Waistcoat": "Clt_VST005",
    "Fishing Vest": "Clt_VST007",
    "Front Zip Vest": "Clt_VST008",
    "Silver Tentatek Vest": "Clt_VST009",
    "Comeback": "ComeBack",
    "Haunt": "DeathMarking",
    "Durability": "Defence",
    "Last-Ditch Effort": "EndAllUp",
    "Ability Doubler": "ExSkillDouble",
    "Respawn Punisher": "Exorcist",
    "Impact": "Explosion",
    "Squid Beakon": "Flag",
    "Port Mackerel": "Fld_Amida01_Vss",
    "Camp Triggerfish": "Fld_Athletic01_Vss",
    "Wahoo World": "Fld_Carousel00_Vss",
    "Goby Arena": "Fld_Court00_Vss",
    "Shifty Station": "Fld_Deli_Vss",
    "The Reef": "Fld_Ditch02_Vss",
    "Snapper Canal": "Fld_Kawa00_Vss",
    "MakoMart": "Fld_Line00_Vss",
    "Kelp Dome": "Fld_Maze02_Vss",
    "Skipper Pavilion": "Fld_Mirror00_Vss",
    "Sturgeon Shipyard": "Fld_Nagasaki00_Vss",
    "New Albacore Hotel": "Fld_Nakasu00_Vss",
    "Ancho-V Games": "Fld_Office01_Vss",
    "Manta Maria": "Fld_Pillar00_Vss",
    "Piranha Pit": "Fld_Quarry01_Vss",
    "Lost Outpost": "Fld_Shakehouse00_Cop",
    "Salmonid Smokeyard": "Fld_Shakelift00_Cop",
    "Ruins of Ark Polaris": "Fld_Shakeride00_Cop",
    "Marooner's Bay": "Fld_Shakeship00_Cop",
    "Spawning Grounds": "Fld_Shakeup00_Cop",
    "Blackbelly Skatepark": "Fld_SkatePark02_Vss",
    "Shellendorf Institute": "Fld_Tunnel00_Vss",
    "Moray Towers": "Fld_Tuzura00_Vss",
    "Musselforge Fitness": "Fld_Unduck00_Vss",
    "Arowana Mall": "Fld_UpDown01_Vss",
    "Inkblot Art Academy": "Fld_Upland00_Vss",
    "Starfish Mainstage": "Fld_Venue02_Vss",
    "Walleye Warehouse": "Fld_Warehouse01_Vss",
    "Humpback Pump Track": "Fld_Wave00_Vss",
    "Eminence Cuff": "Hed_ACC001",
    "Squid Hairclip": "Hed_AMB000",
    "Samurai Helmet": "Hed_AMB001",
    "Power Mask": "Hed_AMB002",
    "Squid Clip-Ons": "Hed_AMB003",
    "Squinja Mask": "Hed_AMB004",
    "Power Mask Mk I": "Hed_AMB005",
    "Pearlescent Crown": "Hed_AMB006",
    "Marinated Headphones": "Hed_AMB007",
    "Enchanted Hat": "Hed_AMB008",
    "Steel Helm": "Hed_AMB009",
    "Fresh Fish Head": "Hed_AMB010",
    "Urchins Cap": "Hed_CAP000",
    "Lightweight Cap": "Hed_CAP001",
    "Takoroka Mesh": "Hed_CAP002",
    "Streetstyle Cap": "Hed_CAP003",
    "Squid-Stitch Cap": "Hed_CAP004",
    "Squidvader Cap": "Hed_CAP005",
    "Camo Mesh": "Hed_CAP006",
    "Five-Panel Cap": "Hed_CAP007",
    "Zekko Mesh": "Hed_CAP008",
    "Backwards Cap": "Hed_CAP009",
    "Two-Stripe Mesh": "Hed_CAP010",
    "Jet Cap": "Hed_CAP011",
    "Cycling Cap": "Hed_CAP012",
    "Cycle King Cap": "Hed_CAP014",
    "Legendary Cap": "Hed_CAP015",
    "Long-Billed Cap": "Hed_CAP018",
    "King Flip Mesh": "Hed_CAP019",
    "Hickory Work Cap": "Hed_CAP020",
    "Woolly Urchins Classic": "Hed_CAP021",
    "Jellyvader Cap": "Hed_CAP023",
    "House-Tag Denim Cap": "Hed_CAP024",
    "Blowfish Newsie": "Hed_CAP025",
    "Do-Rag, Cap, & Glasses": "Hed_CAP026",
    "Pilot Hat": "Hed_CAP027",
    "Headlamp Helmet": "Hed_COP100",
    "Dust Blocker 2000": "Hed_COP101",
    "Welding Mask": "Hed_COP102",
    "Beekeeper Hat": "Hed_COP103",
    "Octoleet Goggles": "Hed_COP104",
    "Cap of Legend": "Hed_COP105",
    "Oceanic Hard Hat": "Hed_COP106",
    "Worker's Head Towel": "Hed_COP107",
    "Sailor Cap": "Hed_COP109",
    "Mecha Head - HTR": "Hed_CRC000",
    "Retro Specs": "Hed_EYE000",
    "Splash Goggles": "Hed_EYE001",
    "Pilot Goggles": "Hed_EYE002",
    "Tinted Shades": "Hed_EYE003",
    "Black Arrowbands": "Hed_EYE004",
    "Snorkel Mask": "Hed_EYE005",
    "White Arrowbands": "Hed_EYE006",
    "Fake Contacts": "Hed_EYE007",
    "18K Aviators": "Hed_EYE008",
    "Full Moon Glasses": "Hed_EYE009",
    "Octoglasses": "Hed_EYE010",
    "Half-Rim Glasses": "Hed_EYE011",
    "Double Egg Shades": "Hed_EYE012",
    "Zekko Cap": "Hed_EYE013",
    "SV925 Circle Shades": "Hed_EYE014",
    "Annaki Beret & Glasses": "Hed_EYE015",
    "Swim Goggles": "Hed_EYE016",
    "Ink-Guard Goggles": "Hed_EYE017",
    "Toni Kensa Goggles": "Hed_EYE018",
    "Sennyu Goggles": "Hed_EYE019",
    "Sennyu Specs": "Hed_EYE020",
    "White Headband": "Hed_FST000",
    "Kyonshi Hat": "Hed_HAP000",
    "Li'l Devil Horns": "Hed_HAP001",
    "Hockey Mask": "Hed_HAP002",
    "Anglerfish Mask": "Hed_HAP003",
    "Festive Party Cone": "Hed_HAP004",
    "New Year's Glasses DX": "Hed_HAP005",
    "Twisty Headband": "Hed_HAP006",
    "Eel-Cake Hat": "Hed_HAP007",
    "Purple Novelty Visor": "Hed_HAP008",
    "Green Novelty Visor": "Hed_HAP009",
    "Orange Novelty Visor": "Hed_HAP010",
    "Pink Novelty Visor": "Hed_HAP011",
    "Safari Hat": "Hed_HAT000",
    "Jungle Hat": "Hed_HAT001",
    "Camping Hat": "Hed_HAT002",
    "Blowfish Bell Hat": "Hed_HAT003",
    "Bamboo Hat": "Hed_HAT004",
    "Straw Boater": "Hed_HAT005",
    "Classic Straw Boater": "Hed_HAT006",
    "Treasure Hunter": "Hed_HAT007",
    "Bucket Hat": "Hed_HAT008",
    "Patched Hat": "Hed_HAT009",
    "Tulip Parasol": "Hed_HAT010",
    "Fugu Bell Hat": "Hed_HAT011",
    "Seashell Bamboo Hat": "Hed_HAT012",
    "Hothouse Hat": "Hed_HAT013",
    "Mountie Hat": "Hed_HAT014",
    "B-ball Headband": "Hed_HBD001",
    "Squash Headband": "Hed_HBD002",
    "Tennis Headband": "Hed_HBD003",
    "Jogging Headband": "Hed_HBD004",
    "Soccer Headband": "Hed_HBD005",
    "FishFry Biscuit Bandana": "Hed_HBD007",
    "Black FishFry Bandana": "Hed_HBD008",
    "Studio Headphones": "Hed_HDP000",
    "Designer Headphones": "Hed_HDP001",
    "Noise Cancelers": "Hed_HDP002",
    "Squidfin Hook Cans": "Hed_HDP003",
    "Squidlife Headphones": "Hed_HDP004",
    "Studio Octophones": "Hed_HDP005",
    "Sennyu Headphones": "Hed_HDP006",
    "Bike Helmet": "Hed_MET000",
    "Stealth Goggles": "Hed_MET002",
    "Tentacles Helmet": "Hed_MET003",
    "Skate Helmet": "Hed_MET004",
    "Visor Skate Helmet": "Hed_MET005",
    "MTB Helmet": "Hed_MET006",
    "Hockey Helmet": "Hed_MET007",
    "Matte Bike Helmet": "Hed_MET008",
    "Octo Tackle Helmet Deco": "Hed_MET009",
    "Moist Ghillie Helmet": "Hed_MET010",
    "Deca Tackle Visor Helmet": "Hed_MET011",
    "Gas Mask": "Hed_MSK000",
    "Paintball Mask": "Hed_MSK001",
    "Paisley Bandana": "Hed_MSK002",
    "Skull Bandana": "Hed_MSK003",
    "Painter's Mask": "Hed_MSK004",
    "Annaki Mask": "Hed_MSK005",
    "Octoking Facemask": "Hed_MSK006",
    "Squid Facemask": "Hed_MSK007",
    "Firefin Facemask": "Hed_MSK008",
    "King Facemask": "Hed_MSK009",
    "Motocross Nose Guard": "Hed_MSK010",
    "Forge Mask": "Hed_MSK011",
    "Digi-Camo Forge Mask": "Hed_MSK012",
    "Koshien Bandana": "Hed_MSK013",
    "Hero Headset Replica": "Hed_MSN000",
    "Armor Helmet Replica": "Hed_MSN004",
    "Hero Headphones Replica": "Hed_MSN101",
    "Octoling Shades": "Hed_MSN104",
    "Null Visor Replica": "Hed_MSN105",
    "Old-Timey Hat": "Hed_MSN106",
    "Conductor Cap": "Hed_MSN107",
    "Golden Toothpick": "Hed_MSN108",
    "Bobble Hat": "Hed_NCP000",
    "Short Beanie": "Hed_NCP001",
    "Striped Beanie": "Hed_NCP002",
    "Sporty Bobble Hat": "Hed_NCP003",
    "Special Forces Beret": "Hed_NCP004",
    "Squid Nordic": "Hed_NCP005",
    "Sennyu Bon Bon Beanie": "Hed_NCP006",
    "Knitted Hat": "Hed_NCP008",
    "Annaki Beret": "Hed_NCP009",
    "Yamagiri Beanie": "Hed_NCP010",
    "Sneaky Beanie": "Hed_NCP011",
    "Octoling Goggles": "Hed_RVL000",
    "Golf Visor": "Hed_VIS000",
    "FishFry Visor": "Hed_VIS001",
    "Sun Visor": "Hed_VIS002",
    "Takoroka Visor": "Hed_VIS003",
    "Face Visor": "Hed_VIS004",
    "Run Speed Up": "HumanMove_Up",
    "Ink Recovery Up": "InkRecovery_Up",
    "Inkjet": "Jetpack",
    "Quick Super Jump": "JumpTime_Save",
    "Curling-Bomb Launcher": "LauncherCurling",
    "Burst-Bomb Launcher": "LauncherQuick",
    "Autobomb Launcher": "LauncherRobo",
    "Splat-Bomb Launcher": "LauncherSplash",
    "Suction-Bomb Launcher": "LauncherSuction",
    "Slightly increases\nmovement speed\nwhile inking.": "MPU_BrushSpeedUp",
    "Increases Brella\ncanopy durability.": "MPU_CanopyHPUp",
    "Speeds up Brella\ncanopy regeneration.": "MPU_CanopyRecoveryUp",
    "Increases high-damage\nradius of explosions.": "MPU_DamageAreaUp",
    "Increases maximum\ndamage range.": "MPU_DamageReductionDown",
    "Increases damage.": "MPU_DamageUp",
    "Increases ink coverage.": "MPU_PaintUp",
    "Slightly increases range.": "MPU_RangeUp",
    "Increases shot accuracy\nwhen firing while jumping.": "MPU_ReduceDegJump",
    "Increases duration of\nfiring in a burst.": "MPU_ShootingFrameUp",
    "Ink Saver (Main)": "MainInk_Save",
    "Main Power Up": "MarkingTime_Reduction",
    "Tenacity": "MinorityUp",
    "Cannon": "MissileMissilePosition",
    "Mobility": "Mobility",
    "Object Shredder": "ObjectEffect_Up",
    "Ink Resistance Up": "OpInkEffect_Reduction",
    "Ink Speed": "PaintSpeed",
    "Point Sensor": "PointSensor",
    "Toxic Mist": "PoisonFog",
    "Damage": "Power",
    "Ink Storm": "RainCloud",
    "Range": "Range",
    "Special Saver": "RespawnSpecialGauge_Save",
    "Quick Respawn": "RespawnTime_Save",
    "Inkbrush": "Roller_BrushMini_00",
    "Inkbrush Nouveau": "Roller_BrushMini_01",
    "Permanent Inkbrush": "Roller_BrushMini_02",
    "Octobrush": "Roller_BrushNormal_00",
    "Octobrush Nouveau": "Roller_BrushNormal_01",
    "Kensa Octobrush": "Roller_BrushNormal_02",
    "Herobrush Replica": "Roller_BrushNormal_H",
    "Carbon Roller": "Roller_Compact_00",
    "Carbon Roller Deco": "Roller_Compact_01",
    "Dynamo Roller": "Roller_Heavy_00",
    "Gold Dynamo Roller": "Roller_Heavy_01",
    "Kensa Dynamo Roller": "Roller_Heavy_02",
    "Flingza Roller": "Roller_Hunter_00",
    "Foil Flingza Roller": "Roller_Hunter_01",
    "Herobrush": "Roller_MissionBrushNormalLv1",
    "Hero Roller": "Roller_MissionNormalLv1",
    "Splat Roller": "Roller_Normal_00",
    "Krak-On Splat Roller": "Roller_Normal_01",
    "Kensa Splat Roller": "Roller_Normal_02",
    "Hero Roller Replica": "Roller_Normal_H",
    "Reduces damage taken by\nblasts from non-main\nweapons, and reduces\nthe time you're tracked.": "SE_BombDamage_Reduction",
    "Upgrades your\nsub weapon.": "SE_BombDistance_Up",
    "Boosts some of your\nabilities for a short\ntime after respawning.": "SE_ComeBack",
    "Once you've respawned,\nreveals the position of\nplayers who've splatted\nyou.": "SE_DeathMarking",
    "Boosts ink recovery\nrate and weapon ink\nefficiency for the last\n30 seconds of battle.": "SE_EndAllUp",
    "Doubles the effect of\nother gear abilities\nattached to this gear.": "SE_ExSkillDouble",
    "Increases respawn time\nand special-gauge spawn\npenalty for you and any\nplayer you splat.": "SE_Exorcist",
    "Increases movement\nspeed in Inkling form.": "SE_HumanMove_Up",
    "Increases ink-tank refill\nrate.": "SE_InkRecovery_Up",
    "Increases Super Jump\nspeed.": "SE_JumpTime_Save",
    "Decreases amount\nof ink consumed by\nyour main weapon.": "SE_MainInk_Save",
    "[\u000e\u0004\u0000\u0004\u0000\ucd00]\n\u000e\u0004\u0005\u0000": "SE_MarkingTime_Reduction",
    "Upgrades your\nmain weapon.": "SE_MarkingTime_Reduction_Default",
    "Fills special gauge\nautomatically if your\nteam has fewer active\nplayers than the enemy.": "SE_MinorityUp",
    "Increases damage dealt\nto all non-player targets.": "SE_ObjectEffect_Up",
    "Reduces damage taken\nand improves mobility\nwhen walking through\nenemy ink.": "SE_OpInkEffect_Reduction",
    "Reduces special-gauge\ndecrease after getting\nsplatted.": "SE_RespawnSpecialGauge_Save",
    "Reduces respawn time\nafter getting splatted\nrepeatedly without\nsplatting any opponents.": "SE_RespawnTime_Save",
    "Tilting the L Stick during\na Super Jump allows you\nto perform a roll in that\ndirection when landing.": "SE_SomersaultLanding",
    "Increases special-\ngauge fill rate.": "SE_SpecialIncrease_Up",
    "Upgrades your\nspecial weapon.": "SE_SpecialTime_Up",
    "Leaves no trace when\nswimming in inked\nground, but slightly\nreduces swim speed.": "SE_SquidMoveSpatter_Reduction",
    "Increases movement\nspeed in squid form.": "SE_SquidMove_Up",
    "Boosts your speed while\nmoving for the first 30\nseconds of battle.": "SE_StartAllUp",
    "Decreases amount\nof ink consumed by\nyour sub weapon.": "SE_SubInk_Save",
    "Hides your Super Jump\nlanding point from\ndistant players.": "SE_SuperJumpSign_Hide",
    "Allows you to track\ndistant players hit with\nshots from your main\nweapon.": "SE_ThermalInk",
    "Unlock this ability by\nbattling while wearing\nthis gear.": "SE_Unknown",
    "Rainmaker": "cVgl_2L",
    "Splash Wall": "Shield",
    "Grizzco Blaster": "Shooter_BlasterCoopBurst",
    "Rapid Blaster Pro": "Shooter_BlasterLightLong_00",
    "Rapid Blaster Pro Deco": "Shooter_BlasterLightLong_01",
    "Clash Blaster": "Shooter_BlasterLightShort_00",
    "Clash Blaster Neo": "Shooter_BlasterLightShort_01",
    "Rapid Blaster": "Shooter_BlasterLight_00",
    "Rapid Blaster Deco": "Shooter_BlasterLight_01",
    "Kensa Rapid Blaster": "Shooter_BlasterLight_02",
    "Range Blaster": "Shooter_BlasterLong_00",
    "Custom Range Blaster": "Shooter_BlasterLong_01",
    "Grim Range Blaster": "Shooter_BlasterLong_02",
    "Blaster": "Shooter_BlasterMiddle_00",
    "Custom Blaster": "Shooter_BlasterMiddle_01",
    "Hero Blaster Replica": "Shooter_BlasterMiddle_H",
    "Hero Blaster": "Shooter_BlasterMissionMiddleLv1",
    "Luna Blaster": "Shooter_BlasterShort_00",
    "Luna Blaster Neo": "Shooter_BlasterShort_01",
    "Kensa Luna Blaster": "Shooter_BlasterShort_02",
    "Aerospray MG": "Shooter_Blaze_00",
    "Aerospray RG": "Shooter_Blaze_01",
    "Aerospray PG": "Shooter_Blaze_02",
    "Splattershot Pro": "Shooter_Expert_00",
    "Forge Splattershot Pro": "Shooter_Expert_01",
    "Kensa Splattershot Pro": "Shooter_Expert_02",
    "Splattershot Jr.": "Shooter_First_00",
    "Custom Splattershot Jr.": "Shooter_First_01",
    "Kensa Splattershot Jr.": "Shooter_First_02",
    "Squeezer": "Shooter_Flash_00",
    "Foil Squeezer": "Shooter_Flash_01",
    ".52 Gal": "Shooter_Gravity_00",
    ".52 Gal Deco": "Shooter_Gravity_01",
    "Kensa .52 Gal": "Shooter_Gravity_02",
    ".96 Gal": "Shooter_Heavy_00",
    ".96 Gal Deco": "Shooter_Heavy_01",
    "Jet Squelcher": "Shooter_Long_00",
    "Custom Jet Squelcher": "Shooter_Long_01",
    "Hero Shot": "Shooter_MissionNormalLv2",
    "Splattershot": "Shooter_Normal_00",
    "Tentatek Splattershot": "Shooter_Normal_01",
    "Kensa Splattershot": "Shooter_Normal_02",
    "Hero Shot Replica": "Shooter_Normal_H",
    "Octo Shot Replica": "Shooter_Normal_Oct",
    "Splash-o-matic": "Shooter_Precision_00",
    "Neo Splash-o-matic": "Shooter_Precision_01",
    "N-ZAP '85": "Shooter_QuickMiddle_00",
    "N-ZAP '89": "Shooter_QuickMiddle_01",
    "N-ZAP '83": "Shooter_QuickMiddle_02",
    "Sploosh-o-matic": "Shooter_Short_00",
    "Neo Sploosh-o-matic": "Shooter_Short_01",
    "Sploosh-o-matic 7": "Shooter_Short_02",
    "H-3 Nozzlenose": "Shooter_TripleMiddle_00",
    "H-3 Nozzlenose D": "Shooter_TripleMiddle_01",
    "Cherry H-3 Nozzlenose": "Shooter_TripleMiddle_02",
    "L-3 Nozzlenose": "Shooter_TripleQuick_00",
    "L-3 Nozzlenose D": "Shooter_TripleQuick_01",
    "Kensa L-3 Nozzlenose": "Shooter_TripleQuick_02",
    "School Shoes": "Shs_AMB000",
    "Samurai Shoes": "Shs_AMB001",
    "Power Boots": "Shs_AMB002",
    "Fringed Loafers": "Shs_AMB003",
    "Squinja Boots": "Shs_AMB004",
    "Power Boots Mk I": "Shs_AMB005",
    "Pearlescent Kicks": "Shs_AMB006",
    "Marinated Slip-Ons": "Shs_AMB007",
    "Enchanted Boots": "Shs_AMB008",
    "Steel Greaves": "Shs_AMB009",
    "Fresh Fish Feet": "Shs_AMB010",
    "Moto Boots": "Shs_BOT000",
    "Tan Work Boots": "Shs_BOT001",
    "Red Work Boots": "Shs_BOT002",
    "Blue Moto Boots": "Shs_BOT003",
    "Green Rain Boots": "Shs_BOT004",
    "Acerola Rain Boots": "Shs_BOT005",
    "Punk Whites": "Shs_BOT006",
    "Punk Cherries": "Shs_BOT007",
    "Punk Yellows": "Shs_BOT008",
    "Bubble Rain Boots": "Shs_BOT009",
    "Snowy Down Boots": "Shs_BOT010",
    "Icy Down Boots": "Shs_BOT011",
    "Hunting Boots": "Shs_BOT012",
    "Punk Blacks": "Shs_BOT013",
    "Deepsea Leather Boots": "Shs_BOT014",
    "Moist Ghillie Boots": "Shs_BOT015",
    "Annaki Arachno Boots": "Shs_BOT016",
    "New-Leaf Leather Boots": "Shs_BOT017",
    "Tea-Green Hunting Boots": "Shs_BOT018",
    "Blueberry Casuals": "Shs_CFS000",
    "Plum Casuals": "Shs_CFS001",
    "Angry Rain Boots": "Shs_COP101",
    "Non-slip Senseis": "Shs_COP102",
    "Octoleet Boots": "Shs_COP103",
    "Flipper Floppers": "Shs_COP105",
    "Wooden Sandals": "Shs_COP106",
    "Mecha Legs - LBS": "Shs_CRC000",
    "Cream Basics": "Shs_FST000",
    "Pearl-Scout Lace-Ups": "Shs_HAP000",
    "Pearlescent Squidkid IV": "Shs_HAP001",
    "Pearl Punk Crowns": "Shs_HAP002",
    "New-Day Arrows": "Shs_HAP003",
    "Marination Lace-Ups": "Shs_HAP004",
    "Rina Squidkid IV": "Shs_HAP005",
    "Trooper Power Stripes": "Shs_HAP006",
    "Midnight Slip-Ons": "Shs_HAP007",
    "White Kicks": "Shs_LTS000",
    "Cherry Kicks": "Shs_LTS001",
    "Turquoise Kicks": "Shs_LTS002",
    "Squink Wingtips": "Shs_LTS003",
    "Roasted Brogues": "Shs_LTS004",
    "Kid Clams": "Shs_LTS005",
    "Smoky Wingtips": "Shs_LTS006",
    "Navy Red-Soled Wingtips": "Shs_LTS007",
    "Gray Yellow-Soled Wingtips": "Shs_LTS008",
    "Inky Kid Clams": "Shs_LTS009",
    "Annaki Habaneros": "Shs_LTS010",
    "Annaki Tigers": "Shs_LTS011",
    "Sennyu Inksoles": "Shs_LTS012",
    "Hero Runner Replicas": "Shs_MSN000",
    "Armor Boot Replicas": "Shs_MSN004",
    "Hero Snowboots Replicas": "Shs_MSN101",
    "Neo Octoling Boots": "Shs_MSN104",
    "Null Boots Replica": "Shs_MSN105",
    "Old-Timey Shoes": "Shs_MSN106",
    "Octoling Boots": "Shs_RVL000",
    "Oyster Clogs": "Shs_SDL000",
    "Choco Clogs": "Shs_SDL001",
    "Neon Delta Straps": "Shs_SDL003",
    "Black Flip-Flops": "Shs_SDL004",
    "Snow Delta Straps": "Shs_SDL005",
    "Luminous Delta Straps": "Shs_SDL006",
    "Red FishFry Sandals": "Shs_SDL007",
    "Yellow FishFry Sandals": "Shs_SDL008",
    "Musselforge Flip-Flops": "Shs_SDL009",
    "Red Hi-Horses": "Shs_SHI000",
    "Zombie Hi-Horses": "Shs_SHI001",
    "Cream Hi-Tops": "Shs_SHI002",
    "Purple Hi-Horses": "Shs_SHI003",
    "Hunter Hi-Tops": "Shs_SHI004",
    "Red Hi-Tops": "Shs_SHI005",
    "Gold Hi-Horses": "Shs_SHI006",
    "Shark Moccasins": "Shs_SHI008",
    "Mawcasins": "Shs_SHI009",
    "Chocolate Dakroniks": "Shs_SHI010",
    "Mint Dakroniks": "Shs_SHI011",
    "Black Dakroniks": "Shs_SHI012",
    "Piranha Moccasins": "Shs_SHI013",
    "White Norimaki 750s": "Shs_SHI014",
    "Black Norimaki 750s": "Shs_SHI015",
    "Sunset Orca Hi-Tops": "Shs_SHI016",
    "Red & Black Squidkid IV": "Shs_SHI017",
    "Blue & Black Squidkid IV": "Shs_SHI018",
    "Gray Sea-Slug Hi-Tops": "Shs_SHI019",
    "Orca Hi-Tops": "Shs_SHI020",
    "Milky Enperrials": "Shs_SHI021",
    "Navy Enperrials": "Shs_SHI022",
    "Amber Sea Slug Hi-Tops": "Shs_SHI023",
    "Yellow Iromaki 750s": "Shs_SHI024",
    "Red & White Squidkid V": "Shs_SHI025",
    "Honey & Orange Squidkid V": "Shs_SHI026",
    "Sun & Shade Squidkid IV": "Shs_SHI027",
    "Orca Woven Hi-Tops": "Shs_SHI028",
    "Green Iromaki 750s": "Shs_SHI029",
    "Purple Iromaki 750s": "Shs_SHI030",
    "Red Iromaki 750s": "Shs_SHI031",
    "Blue Iromaki 750s": "Shs_SHI032",
    "Orange Iromaki 750s": "Shs_SHI033",
    "Red Power Stripes": "Shs_SHI034",
    "Blue Power Stripes": "Shs_SHI035",
    "Toni Kensa Black Hi-Tops": "Shs_SHI036",
    "Sesame Salt 270s": "Shs_SHI037",
    "Black & Blue Squidkid V": "Shs_SHI038",
    "Orca Passion Hi-Tops": "Shs_SHI039",
    "Truffle Canvas Hi-Tops": "Shs_SHI040",
    "Online Squidkid V": "Shs_SHI041",
    "Pink Trainers": "Shs_SHT000",
    "Orange Arrows": "Shs_SHT001",
    "Neon Sea Slugs": "Shs_SHT002",
    "White Arrows": "Shs_SHT003",
    "Cyan Trainers": "Shs_SHT004",
    "Blue Sea Slugs": "Shs_SHT005",
    "Red Sea Slugs": "Shs_SHT006",
    "Purple Sea Slugs": "Shs_SHT007",
    "Crazy Arrows": "Shs_SHT008",
    "Black Trainers": "Shs_SHT009",
    "Violet Trainers": "Shs_SHT010",
    "Canary Trainers": "Shs_SHT011",
    "Yellow-Mesh Sneakers": "Shs_SHT012",
    "Arrow Pull-Ons": "Shs_SHT013",
    "Red-Mesh Sneakers": "Shs_SHT014",
    "N-Pacer CaO": "Shs_SHT015",
    "N-Pacer Ag": "Shs_SHT016",
    "N-Pacer Au": "Shs_SHT017",
    "Sea Slug Volt 95s": "Shs_SHT018",
    "Athletic Arrows": "Shs_SHT019",
    "Blue Lo-Tops": "Shs_SLO000",
    "Banana Basics": "Shs_SLO001",
    "LE Lo-Tops": "Shs_SLO002",
    "White Seahorses": "Shs_SLO003",
    "Orange Lo-Tops": "Shs_SLO004",
    "Black Seahorses": "Shs_SLO005",
    "Clownfish Basics": "Shs_SLO006",
    "Yellow Seahorses": "Shs_SLO007",
    "Strapping Whites": "Shs_SLO008",
    "Strapping Reds": "Shs_SLO009",
    "Soccer Shoes": "Shs_SLO010",
    "LE Soccer Shoes": "Shs_SLO011",
    "Sunny Climbing Shoes": "Shs_SLO012",
    "Birch Climbing Shoes": "Shs_SLO013",
    "Green Laceups": "Shs_SLO014",
    "White Laceless Dakroniks": "Shs_SLO015",
    "Blue Laceless Dakroniks": "Shs_SLO016",
    "Suede Gray Lace-Ups": "Shs_SLO017",
    "Suede Nation Lace-Ups": "Shs_SLO018",
    "Suede Marine Lace-Ups": "Shs_SLO019",
    "Toni Kensa Soccer Shoes": "Shs_SLO020",
    "Blue Slip-Ons": "Shs_SLP000",
    "Red Slip-Ons": "Shs_SLP001",
    "Squid-Stitch Slip-Ons": "Shs_SLP002",
    "Polka-dot Slip-Ons": "Shs_SLP003",
    "Trail Boots": "Shs_TRS000",
    "Custom Trail Boots": "Shs_TRS001",
    "Pro Trail Boots": "Shs_TRS002",
    "Bloblobber": "Slosher_Bathtub_00",
    "Bloblobber Deco": "Slosher_Bathtub_01",
    "Grizzco Slosher": "Slosher_CoopVase",
    "Tri-Slosher": "Slosher_Diffusion_00",
    "Tri-Slosher Nouveau": "Slosher_Diffusion_01",
    "Sloshing Machine": "Slosher_Launcher_00",
    "Sloshing Machine Neo": "Slosher_Launcher_01",
    "Kensa Sloshing Machine": "Slosher_Launcher_02",
    "Hero Slosher": "Slosher_MissionStrongLv1",
    "Slosher": "Slosher_Strong_00",
    "Slosher Deco": "Slosher_Strong_01",
    "Soda Slosher": "Slosher_Strong_02",
    "Hero Slosher Replica": "Slosher_Strong_H",
    "Explosher": "Slosher_Washtub_00",
    "Custom Explosher": "Slosher_Washtub_01",
    "Drop Roller": "SomersaultLanding",
    "Special Charge Up": "SpecialIncrease_Up",
    "Special Power Up": "SpecialTime_Up",
    "Ballpoint Splatling": "Spinner_Downpour_00",
    "Ballpoint Splatling Nouveau": "Spinner_Downpour_01",
    "Hydra Splatling": "Spinner_Hyper_00",
    "Custom Hydra Splatling": "Spinner_Hyper_01",
    "Hero Splatling": "Spinner_MissionStandardLv1",
    "Mini Splatling": "Spinner_Quick_00",
    "Zink Mini Splatling": "Spinner_Quick_01",
    "Kensa Mini Splatling": "Spinner_Quick_02",
    "Nautilus 47": "Spinner_Serein_00",
    "Nautilus 79": "Spinner_Serein_01",
    "Heavy Splatling": "Spinner_Standard_00",
    "Heavy Splatling Deco": "Spinner_Standard_01",
    "Heavy Splatling Remix": "Spinner_Standard_02",
    "Hero Splatling Replica": "Spinner_Standard_H",
    "Sprinkler": "Sprinkler",
    "Ninja Squid": "SquidMoveSpatter_Reduction",
    "Swim Speed Up": "SquidMove_Up",
    "Opening Gambit": "StartAllUp",
    "Ink Saver (Sub)": "SubInk_Save",
    "Ink Armor": "SuperArmor",
    "Booyah Bomb": "SuperBall",
    "Bubble Blower": "SuperBubble",
    "Stealth Jump": "SuperJumpSign_Hide",
    "Splashdown": "SuperLanding",
    "Tenta Missiles": "SuperMissile",
    "Ultra Stamp": "SuperStamp",
    "Thermal Ink": "ThermalInk",
    "Ink Mine": "TimerTrap",
    "Dualie Squelchers": "Twins_Dual_00",
    "Custom Dualie Squelchers": "Twins_Dual_01",
    "Glooga Dualies": "Twins_Gallon_00",
    "Glooga Dualies Deco": "Twins_Gallon_01",
    "Kensa Glooga Dualies": "Twins_Gallon_02",
    "Hero Dualies": "Twins_MissionNormalLv1",
    "Splat Dualies": "Twins_Normal_00",
    "Enperry Splat Dualies": "Twins_Normal_01",
    "Kensa Splat Dualies": "Twins_Normal_02",
    "Hero Dualie Replicas": "Twins_Normal_H",
    "Dapple Dualies": "Twins_Short_00",
    "Dapple Dualies Nouveau": "Twins_Short_01",
    "Clear Dapple Dualies": "Twins_Short_02",
    "Dark Tetra Dualies": "Twins_Stepper_00",
    "Light Tetra Dualies": "Twins_Stepper_01",
    "Undercover Brella": "Umbrella_Compact_00",
    "Undercover Sorella Brella": "Umbrella_Compact_01",
    "Kensa Undercover Brella": "Umbrella_Compact_02",
    "Grizzco Brella": "Umbrella_CoopAutoAssault",
    "Hero Brella": "Umbrella_MissionNormalLv1",
    "Splat Brella": "Umbrella_Normal_00",
    "Sorella Brella": "Umbrella_Normal_01",
    "Hero Brella Replica": "Umbrella_Normal_H",
    "Tenta Brella": "Umbrella_Wide_00",
    "Tenta Sorella Brella": "Umbrella_Wide_01",
    "Tenta Camo Brella": "Umbrella_Wide_02",
    "Sting Ray": "WaterCutter",
    "Handling": "Weight",
    "Turf War": "cPnt",
    "Turf\nWar": "cPnt_2L",
    "Splat Zones": "cVar",
    "Splat\nZones": "cVar_2L",
    "Clam Blitz": "cVcl",
    "Clam\nBlitz": "cVcl_2L",
    "Tower Control": "cVlf",
    "Tower\nControl": "cVlf_2L",
}

maps = [
    "The Reef",
    "Musselforge Fitness",
    "Starfish Mainstage",
    "Humpback Pump Track",
    "Inkblot Art Academy",
    "Sturgeon Shipyard",
    "Moray Towers",
    "Port Mackerel",
    "Manta Maria",
    "Kelp Dome",
    "Snapper Canal",
    "Blackbelly Skatepark",
    "MakoMart",
    "Walleye Warehouse",
    "Shellendorf Institute",
    "Arowana Mall",
    "Goby Arena",
    "Piranha Pit",
    "Camp Triggerfish",
    "Wahoo World",
    "New Albacore Hotel",
    "Ancho-V Games",
    "Skipper Pavilion",
]

itz_map_votes = {
    "The Reef": 70,
    "Musselforge Fitness": 56,
    "Starfish Mainstage": 54,
    "Humpback Pump Track": 68,
    "Inkblot Art Academy": 73,
    "Sturgeon Shipyard": 68,
    "Moray Towers": 24,
    "Port Mackerel": 32,
    "Manta Maria": 64,
    "Kelp Dome": 22,
    "Snapper Canal": 63,
    "Blackbelly Skatepark": 57,
    "MakoMart": 79,
    "Walleye Warehouse": 39,
    "Shellendorf Institute": 47,
    "Arowana Mall": 34,
    "Goby Arena": 54,
    "Piranha Pit": 70,
    "Camp Triggerfish": 32,
    "Wahoo World": 73,
    "New Albacore Hotel": 53,
    "Ancho-V Games": 69,
    "Skipper Pavilion": 48,
}

map_part_to_full = {
    "goby": "Goby Arena",
    "piranha": "Piranha Pit",
    "pump": "Humpback Pump Track",
    "snapper": "Snapper Canal",
    "walleye": "Walleye Warehouse",
    "makomart": "MakoMart",
    "arowana": "Arowana Mall",
    "pavilion": "Skipper Pavilion",
    "institute": "Shellendorf Institute",
    "mart": "MakoMart",
    "fitness": "Musselforge Fitness",
    "manta": "Manta Maria",
    "skatepark": "Blackbelly Skatepark",
    "arena": "Goby Arena",
    "mackerel": "Port Mackerel",
    "triggerfish": "Camp Triggerfish",
    "dome": "Kelp Dome",
    "mall": "Arowana Mall",
    "art": "Inkblot Art Academy",
    "new": "New Albacore Hotel",
    "reef": "The Reef",
    "world": "Wahoo World",
    "blackbelly": "Blackbelly Skatepark",
    "pit": "Piranha Pit",
    "musselforge": "Musselforge Fitness",
    "kelp": "Kelp Dome",
    "inkblot": "Inkblot Art Academy",
    "academy": "Inkblot Art Academy",
    "warehouse": "Walleye Warehouse",
    "albacore": "New Albacore Hotel",
    "ancho-v": "Ancho-V Games",
    "anchov": "Ancho-V Games",
    "starfish": "Starfish Mainstage",
    "port": "Port Mackerel",
    "wahoo": "Wahoo World",
    "the": "The Reef",
    "games": "Ancho-V Games",
    "shellendorf": "Shellendorf Institute",
    "mako": "MakoMart",
    "mainstage": "Starfish Mainstage",
    "hotel": "New Albacore Hotel",
    "camp": "Camp Triggerfish",
    "towers": "Moray Towers",
    "sturgeon": "Sturgeon Shipyard",
    "canal": "Snapper Canal",
    "track": "Humpback Pump Track",
    "humpback": "Humpback Pump Track",
    "shipyard": "Sturgeon Shipyard",
    "maria": "Manta Maria",
    "skipper": "Skipper Pavilion",
    "moray": "Moray Towers",
}

mode_part_to_full = {
    "splat zones": "Splat Zones",
    "sz": "Splat Zones",
    "splat": "Splat Zones",
    "zones": "Splat Zones",
    "tower control": "Tower Control",
    "tc": "Tower Control",
    "tower": "Tower Control",
    "control": "Tower Control",
    "rm": "Rainmaker",
    "rain": "Rainmaker",
    "maker": "Rainmaker",
    "rainmaker": "Rainmaker",
    "clam blitz": "Clam Blitz",
    "cb": "Clam Blitz",
    "clam": "Clam Blitz",
    "blitz": "Clam Blitz",
    "clams": "Clam Blitz",
    "turf war": "Turf War",
    "tw": "Turf War",
    "turf": "Turf War",
    "war": "Turf War",
}

abilities_to_emoji = {
    "Bomb Defense Up DX": "<:BombDamage_Reduction:611199201165967400>",
    "Comeback": "<:ComeBack:611199201002651664>",
    "Drop Roller": "<:SomersaultLanding:611199201455636480>",
    "Respawn Punisher": "<:exorcist_noborder:620573311570673674>",
    "Sub Power Up": "<:BombDistance_Up:611199201254047744>",
    "Ink Resistance Up": "<:OpInkEffect_Reduction:611199201090732044>",
    "Ink Recovery Up": "<:InkRecovery_Up:611199201443053578>",
    "Last-Ditch Effort": "<:EndAllUp:611199201019428875>",
    "Opening Gambit": "<:StartAllUp:611199201124286464>",
    "Object Shredder": "<:ObjectEffect_Up:611199201212366848>",
    "Quick Respawn": "<:RespawnTime_Save:611199201300316160>",
    "Ink Saver (Main)": "<:MainInk_Save:611199201178812427>",
    "Ink Saver (Sub)": "<:SubInk_Save:611199201082081316>",
    "Special Saver": "<:RespawnSpecialGauge_Save:611199201317224448>",
    "Quick Super Jump": "<:JumpTime_Save:611199202579709953>",
    "Special Charge Up": "<:SpecialIncrease_Up:611199201291796510>",
    "Run Speed Up": "<:HumanMove_Up:611199201258504204>",
    "Stealth Jump": "<:SuperJumpSign_Hide:611199200872497164>",
    "Swim Speed Up": "<:SquidMove_Up:611199201312768026>",
    "Thermal Ink": "<:ThermalInk:611199201270956062>",
    "Special Power Up": "<:SpecialTime_Up:611199200956252188>",
    "Main Power Up": "<:MarkingTime_Reduction:611199201522614340>",
    "Ninja Squid": "<:SquidMoveSpatter_Reduction:611199202864791562>",
    "Tenacity": "<:MinorityUp:611199200864108545>",
    "Haunt": "<:DeathMarking:611199201338195988>",
    "Ability Doubler": "<:ExSkillDouble:611199201023361055>",
}

abilities_short_to_emoji = {
    "BDU": "<:BombDamage_Reduction:611199201165967400>",
    "CB": "<:ComeBack:611199201002651664>",
    "DR": "<:SomersaultLanding:611199201455636480>",
    "RP": "<:exorcist_noborder:620573311570673674>",
    "BRU": "<:BombDistance_Up:611199201254047744>",
    "RES": "<:OpInkEffect_Reduction:611199201090732044>",
    "REC": "<:InkRecovery_Up:611199201443053578>",
    "LDE": "<:EndAllUp:611199201019428875>",
    "OG": "<:StartAllUp:611199201124286464>",
    "OS": "<:ObjectEffect_Up:611199201212366848>",
    "QR": "<:RespawnTime_Save:611199201300316160>",
    "ISM": "<:MainInk_Save:611199201178812427>",
    "ISS": "<:SubInk_Save:611199201082081316>",
    "SS": "<:RespawnSpecialGauge_Save:611199201317224448>",
    "QSJ": "<:JumpTime_Save:611199202579709953>",
    "SCU": "<:SpecialIncrease_Up:611199201291796510>",
    "RSU": "<:HumanMove_Up:611199201258504204>",
    "SJ": "<:SuperJumpSign_Hide:611199200872497164>",
    "SSU": "<:SquidMove_Up:611199201312768026>",
    "TI": "<:ThermalInk:611199201270956062>",
    "SPU": "<:SpecialTime_Up:611199200956252188>",
    "MPU": "<:MarkingTime_Reduction:611199201522614340>",
    "NS": "<:SquidMoveSpatter_Reduction:611199202864791562>",
    "T": "<:MinorityUp:611199200864108545>",
    "H": "<:DeathMarking:611199201338195988>",
    "AD": "<:ExSkillDouble:611199201023361055>",
}

weapons_to_emoji = {
    "Splattershot Jr.": "<:Shooter_First_00:501520493522714625>",
    "Splash-o-matic": "<:Shooter_Precision_00:501520495506882562>",
    "Aerospray MG": "<:Shooter_Blaze_00:501520498253889558>",
    "Aerospray RG": "<:Shooter_Blaze_01:501520500233601024>",
    "Splattershot": "<:Shooter_Normal_00:501520502008053770>",
    "Tentatek Splattershot": "<:Shooter_Normal_01:501520503635181568>",
    ".52 Gal": "<:Shooter_Gravity_00:501520505011044364>",
    "N-ZAP '85": "<:Shooter_QuickMiddle_00:501520506902675469>",
    "Splattershot Pro": "<:Shooter_Expert_00:501520508844638243>",
    ".96 Gal": "<:Shooter_Heavy_00:501520510748852226>",
    "Jet Squelcher": "<:Shooter_Long_00:501520512384630795>",
    "Luna Blaster": "<:Shooter_BlasterShort_00:501520514091712512>",
    "Blaster": "<:Shooter_BlasterMiddle_00:501520515555393547>",
    "Custom Blaster": "<:Shooter_BlasterMiddle_01:501520517291966467>",
    "Clash Blaster": "<:Shooter_BlasterLightShort_00:501520519649296384>",
    "Rapid Blaster": "<:Shooter_BlasterLight_00:501520521792454666>",
    "L-3 Nozzlenose": "<:Shooter_TripleQuick_00:501520523965104148>",
    "H-3 Nozzlenose": "<:Shooter_TripleMiddle_00:501520525156286465>",
    "Carbon Roller": "<:Roller_Compact_00:501520527522005036>",
    "Splat Roller": "<:Roller_Normal_00:501520529191075840>",
    "Krak-On Splat Roller": "<:Roller_Normal_01:501520531363725312>",
    "Dynamo Roller": "<:Roller_Heavy_00:501520533104361482>",
    "Flingza Roller": "<:Roller_Hunter_00:501520534681550849>",
    "Octobrush": "<:Roller_BrushNormal_00:501520536321392662>",
    "Splat Charger": "<:Charger_Normal_00:501520537999245312>",
    "Firefin Splat Charger": "<:Charger_Normal_01:501520539236564994>",
    "Splatterscope": "<:Charger_NormalScope_00:501520541115613187>",
    "Firefin Splatterscope": "<:Charger_NormalScope_01:501520542587682818>",
    "E-liter 4K": "<:Charger_Long_00:501520544714194976>",
    "E-liter 4K Scope": "<:Charger_LongScope_00:501520547038101553>",
    "Goo Tuber": "<:Charger_Keeper_00:501520548917149729>",
    "Slosher": "<:Slosher_Strong_00:501520550334693394>",
    "Tri-Slosher": "<:Slosher_Diffusion_00:501520552675115019>",
    "Mini Splatling": "<:Spinner_Quick_00:501520554407231498>",
    "Heavy Splatling": "<:Spinner_Standard_00:501520556185878548>",
    "Dapple Dualies": "<:Twins_Short_00:501520558287224842>",
    "Splat Dualies": "<:Twins_Normal_00:501520559788785694>",
    "Enperry Splat Dualies": "<:Twins_Normal_01:501520561571233792>",
    "Inkbrush": "<:Roller_BrushMini_00:501520562980519942>",
    "Dualie Squelchers": "<:Twins_Dual_00:501520565149106178>",
    "Sploosh-o-matic": "<:Shooter_Short_00:501520567011246080>",
    "Splat Brella": "<:Umbrella_Normal_00:501520568592367616>",
    "Classic Squiffer": "<:Charger_Quick_00:501520572552052746>",
    "Sloshing Machine": "<:Slosher_Launcher_00:501520574225580072>",
    "Forge Splattershot Pro": "<:Shooter_Expert_01:501520575802507274>",
    "Custom Splattershot Jr.": "<:Shooter_First_01:501520577723629578>",
    "Heavy Splatling Deco": "<:Spinner_Standard_01:501520579279585331>",
    "Rapid Blaster Pro": "<:Shooter_BlasterLightLong_00:501520581217484800>",
    "Tenta Brella": "<:Umbrella_Wide_00:501520582878167061>",
    "Bamboozler 14 Mk I": "<:Charger_Light_00:501520585512321044>",
    "Custom E-liter 4K Scope": "<:Charger_LongScope_01:501520587181654017>",
    "Custom E-liter 4K": "<:Charger_Long_01:501520588804718592>",
    "Range Blaster": "<:Shooter_BlasterLong_00:501520590323187724>",
    "Gold Dynamo Roller": "<:Roller_Heavy_01:501520592764403734>",
    "Custom Jet Squelcher": "<:Shooter_Long_01:501520594693783552>",
    "Inkbrush Nouveau": "<:Roller_BrushMini_01:501520596484489216>",
    "Foil Flingza Roller": "<:Roller_Hunter_01:501520598153953301>",
    "Hydra Splatling": "<:Spinner_Hyper_00:501520599613702172>",
    "Glooga Dualies": "<:Twins_Gallon_00:501520601236635660>",
    "N-ZAP '89": "<:Shooter_QuickMiddle_01:501520603124334592>",
    "Slosher Deco": "<:Slosher_Strong_01:501520604663513099>",
    "Squeezer": "<:Shooter_Flash_00:501520606437834762>",
    "Undercover Brella": "<:Umbrella_Compact_00:501520608153174028>",
    "Octobrush Nouveau": "<:Roller_BrushNormal_01:501520610409709578>",
    "L-3 Nozzlenose D": "<:Shooter_TripleQuick_01:501520611915333632>",
    "Dapple Dualies Nouveau": "<:Twins_Short_01:501520613320425503>",
    ".52 Gal Deco": "<:Shooter_Gravity_01:501520615623098379>",
    "Rapid Blaster Deco": "<:Shooter_BlasterLight_01:501520618139942912>",
    ".96 Gal Deco": "<:Shooter_Heavy_01:501520620111265792>",
    "Custom Goo Tuber": "<:Charger_Keeper_01:501520621826736128>",
    "Sloshing Machine Neo": "<:Slosher_Launcher_01:501520624305438720>",
    "Luna Blaster Neo": "<:Shooter_BlasterShort_01:501520626226298892>",
    "Dark Tetra Dualies": "<:Twins_Stepper_00:501520628541816893>",
    "Neo Sploosh-o-matic": "<:Shooter_Short_01:501520630273802246>",
    "H-3 Nozzlenose D": "<:Shooter_TripleMiddle_01:501520632052318218>",
    "Sorella Brella": "<:Umbrella_Normal_01:501520635365687297>",
    "Clash Blaster Neo": "<:Shooter_BlasterLightShort_01:501520636959784971>",
    "Tri-Slosher Nouveau": "<:Slosher_Diffusion_01:501520638704484361>",
    "Custom Range Blaster": "<:Shooter_BlasterLong_01:501520640390463489>",
    "Neo Splash-o-matic": "<:Shooter_Precision_01:501520642441478144>",
    "Foil Squeezer": "<:Shooter_Flash_01:501520644257611784>",
    "New Squiffer": "<:Charger_Quick_01:501520646518603777>",
    "Glooga Dualies Deco": "<:Twins_Gallon_01:501520648372355092>",
    "Rapid Blaster Pro Deco": "<:Shooter_BlasterLightLong_01:501520650444341268>",
    "Carbon Roller Deco": "<:Roller_Compact_01:501520652570984474>",
    "Custom Dualie Squelchers": "<:Twins_Dual_01:501520654621868032>",
    "Undercover Sorella Brella": "<:Umbrella_Compact_01:501520656693723157>",
    "Bamboozler 14 Mk II": "<:Charger_Light_01:501520658308661258>",
    "Explosher": "<:Slosher_Washtub_00:501520660217200642>",
    "Ballpoint Splatling": "<:Spinner_Downpour_00:501520661928345632>",
    "Tenta Sorella Brella": "<:Umbrella_Wide_01:501520664554110976>",
    "Bloblobber": "<:Slosher_Bathtub_00:501520666353336330>",
    "Custom Hydra Splatling": "<:Spinner_Hyper_01:501520668425453569>",
    "Nautilus 47": "<:Spinner_Serein_00:501520669956374571>",
    "Light Tetra Dualies": "<:Twins_Stepper_01:501520672200327178>",
    "Kensa Splattershot": "<:Shooter_Normal_02:501520673827586049>",
    "Kensa Splat Roller": "<:Roller_Normal_02:501520676302225410>",
    "Kensa Charger": "<:Charger_Normal_02:501520677938003968>",
    "Kensa Splatterscope": "<:Charger_NormalScope_02:501520679510736896>",
    "Kensa Splat Dualies": "<:Twins_Normal_02:501520680668364801>",
    "Kensa Splattershot Pro": "<:Shooter_Expert_02:501520682174119945>",
    "Kensa Luna Blaster": "<:Shooter_BlasterShort_02:501520685282099201>",
    "Kensa Dynamo Roller": "<:Roller_Heavy_02:501520688612507648>",
    "Kensa Sloshing Machine": "<:Slosher_Launcher_02:501520690516852747>",
    "Kensa Splattershot Jr.": "<:Shooter_First_02:512022728241446917>",
    "Kensa Octobrush": "<:Roller_BrushNormal_02:512022728350498838>",
    "Kensa Undercover Brella": "<:Umbrella_Compact_02:512022728362950667>",
    "Kensa L-3 Nozzlenose": "<:Shooter_TripleQuick_02:512022728505557003>",
    "Custom Explosher": "<:Slosher_Washtub_01:519701391007154188>",
    "Bloblobber Deco": "<:Slosher_Bathtub_01:519701391153823764>",
    "Ballpoint Splatling Nouveau": "<:Spinner_Downpour_01:519701391212544031>",
    "Nautilus 79": "<:Spinner_Serein_01:519701391258812421>",
    "Kensa .52 Gal": "<:Shooter_Gravity_02:519701391959392278>",
    "Kensa Glooga Dualies": "<:Twins_Gallon_02:519701391997141042>",
    "Kensa Rapid Blaster": "<:Shooter_BlasterLight_02:519701392366239745>",
    "Kensa Mini Splatling": "<:Spinner_Quick_02:519701497739477013>",
    "Soda Slosher": "<:Slosher_Strong_02:563043756249579548>",
    "Cherry H-3 Nozzlenose": "<:Shooter_TripleMiddle_02:563043756354306059>",
    "Grim Range Blaster": "<:Shooter_BlasterLong_02:563043756610420786>",
    "Aerospray PG": "<:Shooter_Blaze_02:563043756652232708>",
    "Tenta Camo Brella": "<:Umbrella_Wide_02:563043756664815616>",
    "Fresh Squiffer": "<:Charger_Quick_02:563043756673204234>",
    "N-ZAP '83": "<:Shooter_QuickMiddle_02:563043756685787178>",
    "Clear Dapple Dualies": "<:Twins_Short_02:563043756736118794>",
    "Bamboozler 14 Mk III": "<:Charger_Light_02:563043756748701716>",
    "Permanent Inkbrush": "<:Roller_BrushMini_02:563043757025656844>",
    "Sploosh-o-matic 7": "<:Shooter_Short_02:563043757088571412>",
    "Heavy Splatling Remix": "<:Spinner_Standard_02:563043757549944883>",
    "Zink Mini Splatling": "<:Spinner_Quick_01:501520633436307457>",
    "Hero Blaster Replica": "<:Shooter_BlasterMiddle_H:548478012455125003>",
    "Hero Brella Replica": "<:Umbrella_Normal_H:501520570475872266>",
    "Hero Charger Replica": "<:Charger_Normal_H:548478012622897167>",
    "Hero Dualie Replicas": "<:Twins_Normal_H:548478013075881990>",
    "Hero Roller Replica": "<:Roller_Normal_H:548478012308455436>",
    "Hero Shot Replica": "<:Shooter_Normal_H:548478012639674368>",
    "Hero Slosher Replica": "<:Slosher_Strong_H:548478012572696596>",
    "Hero Splatling Replica": "<:Spinner_Standard_H:548478013080207370>",
    "Herobrush Replica": "<:Roller_BrushNormal_H:548478012585279488>",
    "Octo Shot Replica": "<:Shooter_Normal_Oct:548478123654643732>",
}

modes_to_emoji = {
    "Turf War": "<:turf:594505506417016838>",
    "Splat Zones": "<:sz:524714933389230100>",
    "Tower Control": "<:tc:524714933871706142>",
    "Rainmaker": "<:rm:524714934572023842>",
    "Clam Blitz": "<:cb:524714936165728257>",
    "Ranked Battle": "<:ranked:594822322373001216>",
    "League Battle": "<:league:594822322511151104>",
}

top_500_emoji = "<:top500:594551830764191763>"

found_emoji = "<:found:664548509772546068>"

adjectives = [
    "strange",
    "terrible",
    "chainlike",
    "convivial",
    "fan-leafed",
    "affordable",
    "popular",
    "fabulous",
    "irritating",
    "shiny",
    "comforted",
    "wonderful",
    "skillful",
    "average",
    "exceptionable",
    "arrogant",
    "lazy",
    "biting",
    "wasteful",
    "respectful",
    "gorgeous",
    "vicious",
    "ferocious",
    "good-for-nothing",
    "loving",
    "cheery",
    "orange",
    "illogical",
    "stoic",
    "vast",
    "cloven-hoofed",
    "course",
    "childlike",
    "splendid",
    "hushed",
    "soulful",
    "persnickety",
    "soft",
    "all-devouring",
    "black",
    "well-behaved",
    "comfortless",
    "great",
    "furry",
    "crease-resistant",
    "reclusive",
    "artificial",
    "persistent",
    "slight",
    "closed in",
    "crushing",
    "scary",
    "certifiable",
    "lithe",
    "hard",
    "content",
    "faint",
    "pretend",
    "poor",
    "famous",
    "impressionable",
    "fervent",
    "small",
    "creative",
    "vivid",
    "hope",
    "helpful",
    "bloody",
    "heated up",
    "joyous",
    "painstaking",
    "fragile",
    "quickest",
    "self-assured",
    "sensitive",
    "slippery",
    "unassuming",
    "emotional",
    "passive",
    "center",
    "swift",
    "volcanic",
    "reliable",
    "squeamish",
    "elated",
    "resonant",
    "scrawny",
    "deviant",
    "striped",
    "diplomatic",
    "sneaky",
    "misty",
    "believing",
    "easy",
    "breeze",
    "fanlike",
    "hilarious",
    "fainthearted",
    "good",
    "slimy",
    "borderline",
    "odd",
    "snobby",
    "even-tempered",
    "snazzy",
    "disguised",
    "moronic",
    "meticulous",
    "central american",
    "rotten",
    "blindfolded",
    "orderly",
    "credulous",
    "unpopular",
    "many",
    "misbehaving",
    "gleaming",
    "maternal",
    "divine",
    "all-night",
    "cheering",
    "narrow",
    "fresh",
    "awesome",
    "glued",
    "industrious",
    "moonlit",
    "calm",
    "chivalrous",
    "composed",
    "twisted",
    "lame",
    "sincere",
    "distinct",
    "muddy",
    "cheerful",
    "likeable",
    "efficient",
    "thoughtless",
    "jolly",
    "short",
    "optimistic",
    "frank",
    "haunted",
    "drugged",
    "unthinking",
    "horrible",
    "impressive",
    "late",
    "excellent",
    "difficult",
    "hesitant",
    "quick",
    "barbaric",
    "ordinary",
    "chintzy",
    "glutinous",
    "bungling",
    "restless",
    "stupid",
    "motivated",
    "silly",
    "demoralized",
    "healing",
    "mighty",
    "head-on",
    "curly",
    "artistic",
    "ugliest",
    "immodest",
    "dangerous",
    "hysterical",
    "shrill",
    "broad-minded",
    "annoyed",
    "coal-fired",
    "morose",
    "brokenhearted",
    "resourceful",
    "boiling",
    "shallow",
    "honorable",
    "distant",
    "condescending",
    "deadpan",
    "angry",
    "brainy",
    "evil",
    "free",
    "green",
    "bitter",
    "fluffy",
    "vigilant",
    "husky",
    "disturbed",
    "inspiring",
    "prudent",
    "outrageous",
    "dowdy",
    "gregarious",
    "spine-chilling",
    "steady",
    "hawaiian",
    "sympathetic",
    "distrustful",
    "incisive",
    "blessed",
    "unsure",
    "sophisticated",
    "instinctive",
    "bean-shaped",
    "half-dozen",
    "ratty",
    "grouchy",
    "coincidental",
    "well-respected",
    "itchy",
    "keen",
    "dark",
    "hypercritical",
    "lively",
    "exclusive",
    "chilly",
    "dry",
    "icy",
    "high",
    "clenched",
    "annoying",
    "independent",
    "pokey",
    "super",
    "dramatic",
    "heavy",
    "logical",
    "above average",
    "shaggy",
    "irresistible",
    "high-priced",
    "testy",
    "genuine",
    "eager",
    "sullen",
    "fair-minded",
    "stable",
    "attracted",
    "patient",
    "tricky",
    "involved",
    "ghostly",
    "wary",
    "healthy",
    "experienced",
    "pensive",
    "squealing",
    "cool",
    "flashy",
    "kooky",
    "dated",
    "different",
    "uninterested",
    "cheesy",
    "moody",
    "greasy",
    "smelly",
    "bare-ass",
    "homely",
    "stormy",
    "disappointed",
    "disagreeable",
    "bad",
    "engrossed",
    "witty",
    "caustic",
    "timid",
    "flowing",
    "clever",
    "proud",
    "knowledgeable",
    "doubtful",
    "productive",
    "early",
    "eye-deceiving",
    "appreciative",
    "hearty",
    "grubby",
    "grade-appropriate",
    "polite",
    "dainty",
    "endurable",
    "empowering",
    "stern",
    "grave",
    "cautious",
    "inquisitive",
    "shrewd",
    "bored",
    "disruptive",
    "weak",
    "idiotic",
    "low",
    "unreliable",
    "unguarded",
    "deaf-and-dumb",
    "assertive",
    "boisterous",
    "hardheaded",
    "unbalanced",
    "cooperative",
    "agreeable",
    "steep",
    "shocking",
    "persevering",
    "quick-tempered",
    "elderly",
    "rough",
    "hungry",
    "repulsive",
    "kind",
    "striking",
    "ostentatious",
    "dark-gray",
    "expectant",
    "grotesque",
    "monster",
    "reserved",
    "extreme",
    "modest",
    "leery",
    "placid",
    "ashamed",
    "sentimental",
    "ridiculous",
    "incompetent",
    "chicken",
    "happy-go-lucky",
    "weary",
    "mushy",
    "dusty",
    "quick-witted",
    "enterprising",
    "insensitive",
    "spontaneous",
    "steadfast",
    "mammoth",
    "faithful",
    "sensible",
    "plain",
    "sexy",
    "devoted",
    "discerning",
    "fanciful",
    "raspy",
    "combustive",
    "communicative",
    "receptive",
    "lethargic",
    "young",
    "brief",
    "vigorous",
    "exuberant",
    "enlightened",
    "expedient",
    "hot-headed",
    "big",
    "damn",
    "petulant",
    "screeching",
    "cool-headed",
    "righteous",
    "spinning",
    "prickly",
    "beneficent",
    "nervous",
    "all-round",
    "straightforward",
    "broad",
    "intuitive",
    "geometrical",
    "loyal",
    "revolting",
    "magic",
    "credal",
    "miniature",
    "combinable",
    "unpleasant",
    "affectionate",
    "smokey",
    "enchanting",
    "glinting",
    "uptight",
    "slothful",
    "unfriendly",
    "capable",
    "successful",
    "petite",
    "controlling",
    "outspoken",
    "deafening",
    "gory",
    "tender",
    "triple",
    "shy",
    "demonic",
    "fine",
    "stained",
    "upset",
    "grim",
    "apprehensive",
    "plucky",
    "chaotic",
    "local",
    "made-up",
    "seemly",
    "plain-speaking",
    "numerous",
    "stale",
    "colossal",
    "tight",
    "ancient",
    "defeated",
    "high-level",
    "cordial",
    "juicy",
    "rainy",
    "cobwebby",
    "boney",
    "sociable",
    "excitable",
    "vulnerable",
    "hallucinating",
    "snooping",
    "spotless",
    "succinct",
    "big-shouldered",
    "protective",
    "empowered",
    "brilliant",
    "nosy",
    "ugly",
    "conceited",
    "bloodcurdling",
    "understanding",
    "unimaginative",
    "harmless",
    "burned-out",
    "crucial",
    "gracious",
    "heartbroken",
    "resigned",
    "condemned",
    "dead on target",
    "hot",
    "joyful",
    "dependent",
    "blushing",
    "poised",
    "sparkling",
    "unstable",
    "superficial",
    "wandering",
    "wild",
    "thankful",
    "level-headed",
    "indolent",
    "purring",
    "resolute",
    "stinky",
    "adorable",
    "practical",
    "alarming",
    "thundering",
    "easy-going",
    "lovable",
    "insane",
    "attractive",
    "breakable",
    "hollow",
    "chic",
    "damaged",
    "high-powered",
    "conscientious",
    "honest-to-goodness",
    "very well",
    "spastic",
    "bullying",
    "worried",
    "neat",
    "drooling",
    "whispering",
    "daredevil",
    "provocative",
    "dextrous",
    "reflective",
    "barbecued",
    "serene",
    "best-known",
    "gigantic",
    "tough",
    "indefatigable",
    "frightened",
    "alluring",
    "sulky",
    "ghoulish",
    "suspicious",
    "naked",
    "mild",
    "saucy",
    "cranky",
    "respected",
    "serious",
    "plastic",
    "grieving",
    "pioneering",
    "crafty",
    "bewildered",
    "bell-bottom",
    "boundless",
    "bare-assed",
    "below average",
    "best-selling",
    "sassy",
    "cultured",
    "courageous",
    "heart-healthy",
    "worrisome",
    "intolerant",
    "devilish",
    "direct",
    "embarrassed",
    "stingy",
    "numb",
    "perfect",
    "mature",
    "foolish",
    "groping",
    "childish",
    "quiet",
    "sleepy",
    "graceful",
    "roasted",
    "large",
    "paternalistic",
    "churlish",
    "frightful",
    "dutiful",
    "gifted",
    "demure",
    "crowded",
    "easy going",
    "well",
    "healthful",
    "fiery",
    "pretty",
    "critical",
    "peevish",
    "damned",
    "belligerent",
    "defiant",
    "drowsy",
    "methodical",
    "gossipy",
    "half-size",
    "robust",
    "philosophical",
    "carved",
    "blind drunk",
    "creepy",
    "agile",
    "dark-fruited",
    "spooky",
    "fast",
    "blunt",
    "clean",
    "overjoyed",
    "gullible",
    "fuzzy",
    "liking",
    "dull",
    "bighearted",
    "deep",
    "kind-hearted",
    "dizzy",
    "quaint",
    "combative",
    "cold sober",
    "compassionate",
    "rare",
    "coldhearted",
    "startling",
    "musical",
    "entertaining",
    "festive",
    "warmhearted",
    "combined",
    "sizzling",
    "comfortable",
    "masked",
    "gloomy",
    "inventive",
    "wicked",
    "old-fashioned",
    "broken",
    "sturdy",
    "chilling",
    "envious",
    "gentle",
    "stylish",
    "puny",
    "amiable",
    "innocent",
    "imaginative",
    "frightening",
    "slovenly",
    "darkish",
    "pleasant",
    "somber",
    "moaning",
    "hairy",
    "zany",
    "sudden",
    "peaceful",
    "cute",
    "harsh",
    "sweet",
    "negative",
    "pointed",
    "wooden",
    "ill",
    "circumspect",
    "flat",
    "solid",
    "supportive",
    "shaky",
    "tactless",
    "uneven",
    "glamorous",
    "obedient",
    "depressed",
    "elfin",
    "competent",
    "listless",
    "lusting",
    "guarded",
    "dirty",
    "hateful",
    "gritty",
    "undependable",
    "blue-eyed",
    "cloudy",
    "quarrelsome",
    "excited",
    "glottal",
    "realistic",
    "alien",
    "determined",
    "fancy-free",
    "civil",
    "blinding",
    "attentive",
    "shivering",
    "responsible",
    "dreadful",
    "clinical",
    "interesting",
    "detailed",
    "amicable",
    "exacting",
    "playful",
    "breezy",
    "irascible",
    "prejudiced",
    "thinking",
    "fat",
    "geographic",
    "surly",
    "curious",
    "teasing",
    "silent",
    "centralized",
    "supernatural",
    "warm",
    "encouraging",
    "diligent",
    "well-rounded",
    "staid",
    "precious",
    "black-and-tan",
    "bizarre",
    "nice",
    "watery",
    "painful",
    "judgmental",
    "mute",
    "amused",
    "inexpensive",
    "picky",
    "forceful",
    "handsome",
    "impartial",
    "better",
    "sour",
    "modern",
    "british",
    "subtle",
    "curved",
    "howling",
    "shadowy",
    "ambitious",
    "adventurous",
    "combinatory",
    "morbid",
    "dynamic",
    "abnormal",
    "skinny",
    "cruel",
    "pride",
    "naughty",
    "tasteless",
    "hippie",
    "handwritten",
    "little",
    "comatose",
    "motionless",
    "meddlesome",
    "mysterious",
    "talented",
    "tactful",
    "bushy",
    "guilt-ridden",
    "gruesome",
    "cold",
    "inactive",
    "angelic",
    "giant",
    "empty",
    "yummy",
    "long",
    "overcome",
    "glistening",
    "evasive",
    "dashing",
    "biweekly",
    "stimulating",
    "smart",
    "otherworldly",
    "gobsmacked",
    "brave",
    "unnatural",
    "lovely",
    "real",
    "proficient",
    "thrilled",
    "bold",
    "blissful",
    "fair-and-square",
    "square",
    "lucky",
    "light",
    "fair",
    "happy",
    "querulous",
    "tidy",
    "love-lorn",
    "buff",
    "thrilling",
    "silky",
    "vivacious",
    "careful",
    "yellow",
    "chancy",
    "cowardly",
    "charming",
    "gasping",
    "important",
    "pro-active",
    "candid",
    "powerful",
    "afraid",
    "decisive",
    "grisly",
    "beetle-browed",
    "wide-eyed",
    "fantabulous",
    "half-crazed",
    "imperturbable",
    "smooth",
    "wrong",
    "selfish",
    "harmonious",
    "unsightly",
    "clear",
    "screaming",
    "unemotional",
    "romantic",
    "distraught",
    "unnerving",
    "cuddly",
    "hair-raising",
    "clumsy",
    "loose",
    "concerned",
    "delicious",
    "beatable",
    "positive",
    "careless",
    "dazzling",
    "passionate",
    "sedate",
    "disgusted",
    "factory-made",
    "jittery",
    "inconsiderate",
    "touchy",
    "obnoxious",
    "lonely",
    "demolished",
    "voiceless",
    "closed-circuit",
    "freezing",
    "indiscreet",
    "warming",
    "frail",
    "strong",
    "colorful",
    "sneering",
    "credible",
    "versatile",
    "sloppy",
    "thoughtful",
    "tranquil",
    "dead-on",
    "enthusiastic",
    "unearthly",
    "tolerant",
    "busy",
    "thrifty",
    "upbeat",
    "nutty",
    "rich",
    "magnificent",
    "victorious",
    "easygoing",
    "farming",
    "spicy",
    "salty",
    "crabby",
    "relieved",
    "friendly",
    "cantankerous",
    "grumpy",
    "aggressive",
    "unmotivated",
    "purple",
    "eye-rolling",
    "crystal clear",
    "immature",
    "zealous",
    "combustible",
    "resentful",
    "cherry-sized",
    "well-developed",
    "reassuring",
    "dead",
    "unhelpful",
    "smoggy",
    "confident",
    "inconsistent",
    "fastidious",
    "immense",
    "heartsick",
    "well-intentioned",
    "expensive",
    "nasty",
    "beaten",
    "honest-to-god",
    "dog like",
    "level",
    "melodic",
    "candy",
    "god-awful",
    "fortunate",
    "beefed-up",
    "awful",
    "hard-working",
    "smiling",
    "unsophisticated",
    "exasperating",
    "hissing",
    "tasty",
    "jealous",
    "tiny",
    "delightful",
    "self-disciplined",
    "fierce",
    "scattered",
    "damp",
    "sticky",
    "frantic",
    "reluctant",
    "chewable",
    "staring",
    "considerate",
    "ghastly",
    "wide",
    "coherent",
    "cloak-and-dagger",
    "impatient",
    "impulsive",
    "eminent",
    "miserable",
    "terrifying",
    "slow",
    "bumpy",
    "bright",
    "tall",
    "awkward",
    "filthy",
    "wet",
    "elegant",
    "animated",
    "outgoing",
    "weird",
    "hairless",
    "belated",
    "bone-dry",
    "groveling",
    "combatant",
    "fusion",
    "alert",
    "mean",
    "make-believe",
    "faith",
    "troubled",
    "handsewn",
    "fighting",
    "sore",
    "humorous",
    "cold-blooded",
    "amazing",
    "impractical",
    "unwilling",
    "fancy",
    "supercilious",
    "long-winded",
    "open",
    "revered",
    "huge",
    "energetic",
    "rapid",
    "rational",
    "crazy",
    "glorious",
    "fantastic",
    "uncooperative",
    "mercurial",
    "fussy",
    "uncertain",
    "heartfelt",
    "normal",
    "massive",
    "watchful",
    "new",
    "delicate",
    "beautiful",
    "extraordinary",
    "sharp",
    "bigheaded",
    "honest",
    "crooked",
    "eerie",
    "amusing",
    "best",
    "anxious",
    "discreet",
    "self-confident",
    "soulless",
    "ripe",
    "intent",
    "balanced",
    "punctual",
    "flaky",
    "goosey",
    "willing",
    "spirited",
    "loud",
    "groggy",
    "breathless",
    "courteous",
    "inappropriate",
    "spotty",
    "generous",
    "amazed",
    "puzzled",
    "drunk",
    "businesslike",
    "unusual",
    "flighty",
    "hallucinogenic",
    "distracted",
    "straight",
]
